package edu.university.ops.shared.notification;

/** Notification catalogue (AGENT.md §19), plus a few types the lifecycle needs. */
public enum NotificationType {
    ABSENCE_SUBMITTED,
    ABSENCE_APPROVAL_REQUIRED,
    ABSENCE_APPROVED,
    ABSENCE_REJECTED,
    ABSENCE_RETURNED,
    ABSENCE_CANCELLED,

    TRAVEL_SUBMITTED,
    TRAVEL_APPROVAL_REQUIRED,
    TRAVEL_AUTHORIZED,
    TRAVEL_REJECTED,
    TRAVEL_RETURNED,
    TRAVEL_EXPENSE_REVIEW_REQUIRED,
    TRAVEL_SETTLED,

    TIME_CORRECTION_REQUIRED,
    TIME_CORRECTION_APPROVED,
    TIME_CORRECTION_REJECTED,
    TIME_MONTH_CLOSED_CHANGED,

    TASK_REMINDER,
    BATCH_FAILURE,
    INTEGRATION_FAILURE
}
